language: python

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

install:
  - conda install -c conda-forge python=3.7 numpy scipy tqdm h5py psutil numba sortedcollections openmp pathlib2 setuptools scikit-build
  - conda info -a

script:
  - python setup.py install
  - cd examples
  - python -c "import foam_ct_phantom"